# SPDX-License-Identifier: Apache-2.0
# West YAML manifest for Zephyr as Xen Dom0

manifest:
  self:
    path: zephyr-dom0-xt

  remotes:
    - name: xentroops
      url-base: https://github.com/xen-troops/
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos/
    - name: yhamamachi
      url-base: https://github.com/yhamamachi/
    - name: soburi
      url-base: https://github.com/soburi/

  projects:
    - name: zephyr
      remote: yhamamachi
      revision: v4.2-branch-sh
      west-commands: scripts/west-commands.yml
    - name: zephyr-xenlib
      remote: soburi
      revision: integrate-to-zephyr-repo
    - name: fatfs
      remote: zephyrproject-rtos
      revision: 427159bf95ea49b7680facffaa29ad506b42709b
    - name: zephyr-xrun
      remote: xentroops
      revision: main
